---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
dependencies:
  - biopython=1.87
  - polars=1.43.2
  - python=3.12
